// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.enjaz.busguide

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class PigeonUserDetails (
  val userId: String? = null,
  val email: String? = null,
  val name: String? = null,
  val photoUrl: String? = null,
  val provider: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PigeonUserDetails {
      val userId = list[0] as String?
      val email = list[1] as String?
      val name = list[2] as String?
      val photoUrl = list[3] as String?
      val provider = list[4] as String?
      return PigeonUserDetails(userId, email, name, photoUrl, provider)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      userId,
      email,
      name,
      photoUrl,
      provider,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PigeonAuthResult (
  val success: Boolean,
  val user: PigeonUserDetails? = null,
  val error: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PigeonAuthResult {
      val success = list[0] as Boolean
      val user: PigeonUserDetails? = (list[1] as List<Any?>?)?.let {
        PigeonUserDetails.fromList(it)
      }
      val error = list[2] as String?
      return PigeonAuthResult(success, user, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      success,
      user?.toList(),
      error,
    )
  }
}

@Suppress("UNCHECKED_CAST")
private object AuthApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonAuthResult.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonUserDetails.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PigeonAuthResult -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is PigeonUserDetails -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AuthApi {
  fun loginWithGoogle(callback: (Result<PigeonUserDetails?>) -> Unit)
  // ⚠️ Facebook login disabled
  // fun loginWithFacebook(callback: (Result<PigeonUserDetails?>) -> Unit)
  fun logout(callback: (Result<PigeonAuthResult>) -> Unit)

  companion object {
    /** The codec used by AuthApi. */
    val codec: MessageCodec<Any?> by lazy {
      AuthApiCodec
    }
    /** Sets up an instance of `AuthApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: AuthApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.enjaz7.AuthApi.loginWithGoogle", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.loginWithGoogle() { result: Result<PigeonUserDetails?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      // Facebook login handler disabled
      /*
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.enjaz7.AuthApi.loginWithFacebook", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.loginWithFacebook() { result: Result<PigeonUserDetails?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      */
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.enjaz7.AuthApi.logout", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.logout() { result: Result<PigeonAuthResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
