// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUCkcQI8-F2z2sEjWidK3vkgTtG-E99a0',
    appId: '1:635670015942:web:0510ba496203257dde0cc7',
    messagingSenderId: '635670015942',
    projectId: 'enjaz7-a49f2',
    authDomain: 'enjaz7-a49f2.firebaseapp.com',
    storageBucket: 'enjaz7-a49f2.firebasestorage.app',
    measurementId: 'G-CS2XXPC8EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAApGehTUv-AjNJO5ByNgBSKdHP25cVdPU',
    appId: '1:635670015942:android:9200813128abad0dde0cc7',
    messagingSenderId: '635670015942',
    projectId: 'enjaz7-a49f2',
    storageBucket: 'enjaz7-a49f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiTslCF8L6oHRdDz3zrVg4zD2_1-HV85k',
    appId: '1:635670015942:ios:9550601ddf14951dde0cc7',
    messagingSenderId: '635670015942',
    projectId: 'enjaz7-a49f2',
    storageBucket: 'enjaz7-a49f2.firebasestorage.app',
    androidClientId: '635670015942-act49qrudqf7jkjbbr5q7avkr8lqqcsn.apps.googleusercontent.com',
    iosClientId: '635670015942-d5rvrh7ron0g8dsfv9fmi4ts0ne62sfi.apps.googleusercontent.com',
    iosBundleId: 'com.enjaz.busguide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiTslCF8L6oHRdDz3zrVg4zD2_1-HV85k',
    appId: '1:635670015942:ios:9550601ddf14951dde0cc7',
    messagingSenderId: '635670015942',
    projectId: 'enjaz7-a49f2',
    storageBucket: 'enjaz7-a49f2.firebasestorage.app',
    androidClientId: '635670015942-act49qrudqf7jkjbbr5q7avkr8lqqcsn.apps.googleusercontent.com',
    iosClientId: '635670015942-d5rvrh7ron0g8dsfv9fmi4ts0ne62sfi.apps.googleusercontent.com',
    iosBundleId: 'com.enjaz.busguide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUCkcQI8-F2z2sEjWidK3vkgTtG-E99a0',
    appId: '1:635670015942:web:23a775722d9d5736de0cc7',
    messagingSenderId: '635670015942',
    projectId: 'enjaz7-a49f2',
    authDomain: 'enjaz7-a49f2.firebaseapp.com',
    storageBucket: 'enjaz7-a49f2.firebasestorage.app',
    measurementId: 'G-M996F9Z54Q',
  );
}
