// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class PigeonUserDetails {
  PigeonUserDetails({
    this.userId,
    this.email,
    this.name,
    this.photoUrl,
    this.provider,
  });

  String? userId;

  String? email;

  String? name;

  String? photoUrl;

  String? provider;

  Object encode() {
    return <Object?>[
      userId,
      email,
      name,
      photoUrl,
      provider,
    ];
  }

  static PigeonUserDetails decode(Object result) {
    result as List<Object?>;
    return PigeonUserDetails(
      userId: result[0] as String?,
      email: result[1] as String?,
      name: result[2] as String?,
      photoUrl: result[3] as String?,
      provider: result[4] as String?,
    );
  }
}

class PigeonAuthResult {
  PigeonAuthResult({
    required this.success,
    this.user,
    this.error,
  });

  bool success;

  PigeonUserDetails? user;

  String? error;

  Object encode() {
    return <Object?>[
      success,
      user?.encode(),
      error,
    ];
  }

  static PigeonAuthResult decode(Object result) {
    result as List<Object?>;
    return PigeonAuthResult(
      success: result[0]! as bool,
      user: result[1] != null
          ? PigeonUserDetails.decode(result[1]! as List<Object?>)
          : null,
      error: result[2] as String?,
    );
  }
}

class _AuthApiCodec extends StandardMessageCodec {
  const _AuthApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is PigeonAuthResult) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is PigeonUserDetails) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return PigeonAuthResult.decode(readValue(buffer)!);
      case 129: 
        return PigeonUserDetails.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class AuthApi {
  /// Constructor for [AuthApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AuthApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _AuthApiCodec();

  Future<PigeonUserDetails?> loginWithGoogle() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.enjaz7.AuthApi.loginWithGoogle', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return (replyList[0] as PigeonUserDetails?);
    }
  }

  // ⚠️ Facebook login disabled - kept for compatibility
  /*
  Future<PigeonUserDetails?> loginWithFacebook() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.enjaz7.AuthApi.loginWithFacebook', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return (replyList[0] as PigeonUserDetails?);
    }
  }
  */

  Future<PigeonAuthResult> logout() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.enjaz7.AuthApi.logout', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as PigeonAuthResult?)!;
    }
  }
}
